name: 'Testing Environments'

on:
    workflow_dispatch:

jobs:
    build_dev:
        name: Build Dev
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              run: echo >> ${{secrets.PORT}} - ${{secrets.DATABASE_URL}} - ${{secrets.NODE_ENV}}
    build_prod:
        name: Build Prod
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout code
              run: echo >> ${{secrets.PORT}} - ${{secrets.DATABASE_URL}} - ${{secrets.NODE_ENV}}
